### ISSUE TITLE
Çiftçi kaybolması

### ISSUE THREAD

**Issue by beautybloodtr** [poyrazinan/Farmer-v6#1]
çiftçi durduk yere bir oyuncunun adasında kayboluyor. Oyuncu /çiftçi yazdığında geri dönmek yerine chate komut listesini atmakta, bu olay tahminimce adaya ekli olan kişilerde yaşanmakta sadece.

**Comment by poyrazinan** [comment]
requreOnline ayarını kapatırsanız sorun düzelir.

**Comment by beautybloodtr** [comment]
Bu çözümü senin çiftçin hakkında birinden duydum, denedim ve işe yaramadı. Hala kaybolmaya devam ediyordu. Başka çiftçi eklentisini kullanmaya karar verdim.
