### ISSUE TITLE
Eklenti eşyaları eksik topluyor.

### ISSUE THREAD

**Issue by Corrsy0** [poyrazinan/Farmer-v6#26]
Örneğin 64 adet örümcek gözü var elimde. Ben bu 64 örümcek gözünü yere attığımda panelde 32 adet gösteriyor. Tekrar attığımda ise 96 olarak gösteriyor. Yani ilk toplama aşamasında eksik topluyor lütfen yardımcı olun.

**Comment by poyrazinan** [comment]
- Kullandığınız farmer sürümü (/ver Farmer yazarak ulaşabilirsiniz)
- Sunucu sürümünüz

Verilerini iletebilir misiniz?

**Comment by Corrsy0** [comment]
Sürüm: Farmer version v6-b000
Sunucu sürümüm: 1.17.1 (Tüm sürümler destekli, taban sürüm 1.17.1)

**Comment by poyrazinan** [comment]
Yaptığım  testler sonucunda Farmer version v6-b001 sürümünde bir hata almadım.
Lütfen güncel sürümü kullanın.
