### ISSUE TITLE
Auto Harvest düzgün çalışmıyor

### ISSUE THREAD

**Issue by ismail20061** [poyrazinan/Farmer-v6#27]
Çiftçi toplayacağı mahsulleri düzgün toplamıyor bazılarını topluyor bazıları kalıyor
Farmer sürüm: [v6-beta-b11](https://github.com/poyrazinan/Farmer-v6/releases/tag/beta)
Sunucu sürümü: 1.18.2

**Comment by poyrazinan** [comment]
Güncel sürümü kullanın

**Comment by ismail20061** [comment]
> Güncel sürümü kullanın

Son sürümde evet açlışıyor ama bana ait olmayan claimi bile topluyor + clamii kaldırsam bile toplamaya devam ediyor 
Konsol da bu hatayı spamlıyor
![image](https://github.com/poyrazinan/Farmer-v6/assets/52345151/481fe7e2-a0e8-445b-ad11-978448812681)

**Comment by poyrazinan** [comment]
- Autoharvest aşağıda belirtilen ürünleri toplar:
(# Available harvests: WHEAT, CARROT, POTATO, PUMPKIN, MELON, BEETROOT, NETHER_WART, SUGAR_CANE, COCOA_BEANS)

- Autoharvest config dosyasında "checkStock: true" ayarını true şekilde kullanmanızı öneririm, eğer sorun yaşıyorsanız false ile deneyebilirsiniz.

> > Güncel sürümü kullanın
> 
> Son sürümde evet açlışıyor ama bana ait olmayan claimi bile topluyor + clamii kaldırsam bile toplamaya devam ediyor Konsol da bu hatayı spamlıyor ![image](https://user-images.githubusercontent.com/52345151/261865303-481fe7e2-a0e8-445b-ad11-978448812681.png)

- "clamii kaldırsam bile toplamaya devam ediyor" = yaptığım testlerde böyle bir sorunla karşılaşmadım.

- hata mesajı ile ilgili güncelleme yapıyorum, yakında paylaşacağım.

Denenen minecraft sürümü: 1.20.1
Java sürümü: 20
GriefPrevention sürümü: 16.18.1
Farmer sürümü: Farmer v6 b-001
