### ISSUE TITLE
Önerilerim var.

### ISSUE THREAD

**Issue by Corrsy0** [poyrazinan/Farmer-v6#29]
-otosat haricinde sadece 1 item e oto sat
-çiftçideki item 100 tane diyelim max kapasite 1000, 100 tanesini satmak isterse vergi dahil ne kadar yapıyor bilgisini göstersin.
-iteme özel toplama ( sadece kaktüs ) gibi

bunları eklentiye güncelleme olarak ekler misiniz?

**Comment by poyrazinan** [comment]
Performans ve kolay kullanımı hedeflediğim için, fikirlerinizi güncelleme planıma dahil etmiyorum.


Önerileriniz için teşekkür ederim.
