### ISSUE TITLE
SpawnerMETA

### ISSUE THREAD

**Issue by ismail20061** [poyrazinan/Farmer-v6#30]
Otomatik spawner öldürücü SpawnerMeta plugininin yarattığı yaratıkları öldürmüyor SpawnerMeta desteği eklenebilir mi?

**Comment by poyrazinan** [comment]
@Amowny zamanın varsa eklemen mümkün mü?

**Comment by Amowny** [comment]
> @Amowny zamanın varsa eklemen mümkün mü?

yarın bakmaya calışcam.

**Comment by Amowny** [comment]
> Otomatik spawner öldürücü SpawnerMeta plugininin yarattığı yaratıkları öldürmüyor SpawnerMeta desteği eklenebilir mi?

Discordunuzu iletirseniz bugün test edilebilir bir sürüm gönderebilirim

**Comment by ismail20061** [comment]
> > Otomatik spawner öldürücü SpawnerMeta plugininin yarattığı yaratıkları öldürmüyor SpawnerMeta desteği eklenebilir mi?
> 
> Discordunuzu iletirseniz bugün test edilebilir bir sürüm gönderebilirim

üzgünüm görmemişim discord ismim mravci
